name: 'NPM with node-sass'
description: 'Run npm target with node-sass'
inputs:
  target:
    description: 'package.json target to run'
    required: true
    default: 'test'
outputs:
  time:
    description: 'The time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
branding:
  icon: 'check-square'
  color: 'orange'
